name: ubuntu-24-docker-test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build and smoke test
        run: docker compose run --rm --build test
